# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("locations", "0002_alter_location_options_alter_location_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["date"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(help_text="Event date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(help_text="Event description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(help_text="Event start date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(help_text="Event time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                error_messages={
                    "max_length": "Event title must be less than 256 characters"
                },
                help_text="Event title",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("date", "location")},
        ),
    ]
