# Generated by Django 4.2.13 on 2024-06-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_alter_event_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="start_date",
        ),
    ]
