# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_options_alter_employee_email_and_more"),
        ("staffSchedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffschedule",
            options={
                "verbose_name": "Staff Schedule",
                "verbose_name_plural": "Staff Schedule",
            },
        ),
        migrations.AlterField(
            model_name="staffschedule",
            name="days",
            field=models.IntegerField(help_text="Enter number of days"),
        ),
        migrations.AlterField(
            model_name="staffschedule",
            name="end_time",
            field=models.TimeField(help_text="Enter end time"),
        ),
        migrations.AlterField(
            model_name="staffschedule",
            name="start_time",
            field=models.TimeField(help_text="Enter start time"),
        ),
        migrations.AlterUniqueTogether(
            name="staffschedule",
            unique_together={("employee", "start_time", "end_time")},
        ),
    ]
