# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("positions", "0002_alter_position_options_alter_position_max_salary_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                help_text="Email of employee", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(help_text="Date of hire of employee"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(help_text="Name of employee", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("email", "position")},
        ),
    ]
