# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(
                error_messages={
                    "blank": "This field is required.",
                    "max_length": "The name is too long. It should be 255 characters or less.",
                },
                help_text="Please Enter the full name of the author",
                max_length=255,
            ),
        ),
    ]
