# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["title"],
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.AlterField(
            model_name="position",
            name="max_salary",
            field=models.IntegerField(help_text="Maximum salary"),
        ),
        migrations.AlterField(
            model_name="position",
            name="min_salary",
            field=models.IntegerField(help_text="Minimum salary"),
        ),
        migrations.AlterField(
            model_name="position",
            name="responsibility",
            field=models.CharField(
                help_text="Responsibility of the position", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="title",
            field=models.CharField(
                error_messages={"unique": "A position with that title already exists."},
                help_text="Title of the position",
                max_length=100,
                unique=True,
            ),
        ),
    ]
