# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_alter_author_options_alter_author_name"),
        ("books", "0001_initial"),
        ("genres", "0002_alter_genre_options_alter_genre_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                blank=True, help_text="Genre of book", to="genres.genre"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="ISBN of book", max_length=13, verbose_name="ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publish_date",
            field=models.DateField(
                error_messages={"required": "Date of publishing is required"},
                help_text="Date of publishing",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="quantity_available",
            field=models.PositiveSmallIntegerField(
                default=0,
                error_messages={"required": "Quantity of book is required"},
                help_text="Quantity of book available",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                error_messages={"required": "Title is required"},
                help_text="Title of book",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "author")},
        ),
    ]
