# Generated by Django 5.0.6 on 2024-05-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookCopies", "0001_initial"),
        ("books", "0002_alter_book_options_alter_book_genre_alter_book_isbn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        error_messages={
                            "empty": "date is required",
                            "invalid": "Please enter a valid date",
                        },
                        help_text="Please select date of acquisition of the book",
                    ),
                ),
                ("condition", models.TextField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
            options={
                "unique_together": {("book", "acquisition_date")},
            },
        ),
        migrations.DeleteModel(
            name="bookCopies",
        ),
    ]
