# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventRegistration", "0001_initial"),
        ("events", "0002_alter_event_options_alter_event_date_and_more"),
        ("patrons", "0002_alter_patron_options_alter_patron_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventregistration",
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
            },
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date of registration"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "patron")},
        ),
    ]
