# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fines", "0001_initial"),
        ("loans", "0002_alter_loan_options_alter_loan_due_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fine",
            options={"ordering": ["loan", "amount"]},
        ),
        migrations.AlterField(
            model_name="fine",
            name="amount",
            field=models.PositiveIntegerField(default=0, help_text="Amount of loan"),
        ),
        migrations.AlterField(
            model_name="fine",
            name="reason",
            field=models.TextField(default="", help_text="Reason for loan"),
        ),
        migrations.AlterUniqueTogether(
            name="fine",
            unique_together={("loan", "amount")},
        ),
    ]
