# Generated by Django 5.0.6 on 2024-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_item', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('requested_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
