# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryRequests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryrequest",
            options={
                "verbose_name": "Inventory Request",
                "verbose_name_plural": "Inventory Requests",
            },
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="quantity",
            field=models.PositiveIntegerField(help_text="How many items do you have?"),
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="requested_date",
            field=models.DateField(help_text="Enter the date of request"),
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="requested_item",
            field=models.CharField(
                help_text="Enter the name of the item", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="status",
            field=models.CharField(
                help_text="Enter the status of the request", max_length=255
            ),
        ),
    ]
