# Generated by Django 4.2.13 on 2024-06-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoryRequests", "0002_alter_inventoryrequest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                    ("FULFILLED", "Fulfilled"),
                ],
                help_text="Enter the status of the request",
                max_length=255,
            ),
        ),
    ]
