# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_alter_book_genre_alter_book_isbn_and_more"),
        ("patrons", "0002_alter_patron_options_alter_patron_address_and_more"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["book", "patron"],
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="expiry_date",
            field=models.DateField(help_text="Date of expiration"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(help_text="Date of reservation"),
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("book", "patron")},
        ),
    ]
