# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["name"],
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(
                error_messages={"invalid": "Enter a valid description"},
                help_text="Enter a description",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                error_messages={"invalid": "Enter a valid genre"},
                help_text="Enter a genre",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="genre",
            unique_together={("name", "description")},
        ),
    ]
