# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patrons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patron",
            options={"verbose_name": "patron", "verbose_name_plural": "patrons"},
        ),
        migrations.AlterField(
            model_name="patron",
            name="address",
            field=models.CharField(help_text="Address of patron", max_length=100),
        ),
        migrations.AlterField(
            model_name="patron",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A patron with this email already exists."},
                help_text="Email of patron",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="patron",
            name="membership_date",
            field=models.DateField(help_text="Date of membership"),
        ),
        migrations.AlterField(
            model_name="patron",
            name="membership_status",
            field=models.CharField(help_text="Status of patron", max_length=100),
        ),
        migrations.AlterField(
            model_name="patron",
            name="name",
            field=models.CharField(help_text="Name of patron", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="patron",
            unique_together={("name", "email")},
        ),
    ]
