# Generated by Django 4.2.13 on 2024-06-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patrons", "0002_alter_patron_options_alter_patron_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patron",
            name="membership_status",
            field=models.CharField(
                choices=[("AC", "Active"), ("EX", "Expired"), ("SU", "Suspended")],
                default="EX",
                help_text="Status of patron",
                max_length=12,
            ),
        ),
    ]
