# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userLogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserLogs",
            new_name="UserLog",
        ),
        migrations.AlterModelOptions(
            name="userlog",
            options={
                "get_latest_by": "date",
                "ordering": ["-date"],
                "verbose_name": "User Logs",
                "verbose_name_plural": "User Logs",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userlog",
            unique_together={("user", "date")},
        ),
    ]
