# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["name"],
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_info",
            field=models.CharField(help_text="Enter your contact info", max_length=100),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(help_text="Enter your name", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together={("name", "contact_info")},
        ),
    ]
