# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_alter_book_genre_alter_book_isbn_and_more"),
        ("loans", "0001_initial"),
        ("patrons", "0002_alter_patron_options_alter_patron_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "ordering": ["return_date"],
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
            },
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_date",
            field=models.DateField(help_text="Date of due"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_date",
            field=models.DateField(help_text="Date of loan"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="return_date",
            field=models.DateField(help_text="Date of return"),
        ),
        migrations.AlterUniqueTogether(
            name="loan",
            unique_together={("book", "patron")},
        ),
    ]
