# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookReviews", "0001_initial"),
        ("books", "0002_alter_book_options_alter_book_genre_alter_book_isbn_and_more"),
        ("patrons", "0002_alter_patron_options_alter_patron_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreview",
            name="rating",
            field=models.IntegerField(default=0, help_text="Enter your rating"),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="review_text",
            field=models.TextField(
                error_messages={"required": "Please enter your review text"},
                help_text="Enter your review text",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookreview",
            unique_together={("book", "patron")},
        ),
    ]
