# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                error_messages={"unique": "A department with that name already exists"},
                help_text="Department Name",
                max_length=100,
                unique=True,
            ),
        ),
    ]
