# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisher",
            options={
                "ordering": ["name"],
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
            },
        ),
        migrations.AlterField(
            model_name="publisher",
            name="address",
            field=models.CharField(
                help_text="The address of the publisher", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="contact",
            field=models.CharField(
                help_text="The contact number of the publisher", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(
                error_messages={"required": "The name must be provided"},
                help_text="The name of the publisher",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publisher",
            unique_together={("name", "contact")},
        ),
    ]
