# Generated by Django 4.2.13 on 2024-06-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_location_options_alter_location_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("LIBRARY", "Library"),
                    ("READING_ROOM", "Reading Room"),
                    ("STORAGE", "Storage"),
                    ("OFFICE", "Office"),
                ],
                help_text="Select Location Type",
                max_length=100,
            ),
        ),
    ]
