# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookOrders", "0001_initial"),
        ("books", "0002_alter_book_options_alter_book_genre_alter_book_isbn_and_more"),
        (
            "supplier",
            "0002_alter_supplier_options_alter_supplier_contact_info_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookorder",
            options={"ordering": ["order_date"]},
        ),
        migrations.AlterField(
            model_name="bookorder",
            name="quantity",
            field=models.IntegerField(
                default=1, help_text="Quantity of order will be one by default"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookorder",
            unique_together={("book", "supplier")},
        ),
    ]
