# Generated by Django 4.2.13 on 2024-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookOrders",
            "0002_alter_bookorder_options_alter_bookorder_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("R", "Received"),
                    ("C", "Cancelled"),
                    ("F", "Fulfilled"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
