# Generated by Django 5.0.6 on 2024-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("patrons", "0002_alter_patron_options_alter_patron_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-date"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(help_text="The message to be displayed"),
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("date", "patron")},
        ),
    ]
